### ISSUE TITLE
Add `no_log` to `docker_deploy_files`

### ISSUE THREAD

**Issue by Tinyblargon** [Tinyblargon/ansible-role-docker-deploy#13]
Add `no_log` to the map in `docker_deploy_files`. For backwards compatibility it should default to `false`.

```yml
docker_deploy_files:
  - dest: ".env"
    src: ".env"
  - dest: ".secrets/password.txt"
    content: "{{ lookup('file', 'password.txt') }}"
    owner: "root"
    group: "root"
    mode: "0600"
    no_log: true
```
